### ISSUE TITLE
Translation: "Base artifact crafting success rate" property

### ISSUE THREAD

**Issue by ucddj** [iguanacore/iguana_acs_fix#49]
The proposed wiki translation: Divine Relic Crafting Base Rate sounds good enough

**Comment by iguanacore** [comment]
Currently, if you fail that related roll for the property, the end result is a Divine Relic tier Item. Does the following sentence make sense?
_If you succeed in the roll utilizing Divine Relic Crafting Base Rate, you get a Sacred Relic (T12 Artifact)._
Considering the possible usage, calling it a `Sacred Relic Crafting Base Rate` would be more accurate, but it would overlap with Shendao Artifacts/Sacred Relics. To avoid overlapping, calling it `T12 Artifact crafting success rate` would be another possibility.
