### ISSUE TITLE
Display bug: Qi regen still showing positive during golden core breakthrough

### ISSUE THREAD

**Issue by ucddj** [iguanacore/iguana_acs_fix#51]
![image](https://github.com/iguanacore/iguana_acs_fix/assets/75850663/96bde080-ea2a-4f09-80ca-ba0ce9e3cdde)

The qi regen is properly disabled but the value of DynamicAddLing is never set to 0 so the last valid value is used. This seems to have been an ongoing source of confusion for beginners.

**Comment by iguanacore** [comment]
As a generalization, the effect from flag FLAG_NOLING isn't displayed properly. Golden Core Breakthroughs are just the main place where it would come up.
Since the display base mental state mod already deals with a factor near this, some effort may already exist toward fixing it.
