### ISSUE TITLE
Translation: Cultivation Speed Bonus

### ISSUE THREAD

**Issue by ucddj** [iguanacore/iguana_acs_fix#55]
Current text: "Cultivation speed gained by Golden Core Cultivators."

Pretty simple change to avoid inducing mistakes.

**Comment by iguanacore** [comment]
Golden Core into Xiandao is a reasonable change, but for the sake of uniformity, might need an additional pass to check and change further similar references.

**Comment by ucddj** [comment]
Good point. Other concerned texts:
* Description of `NpcDiscipleOfJinDan`
* possibly the description of `SuperPart_Gong_1_8` ? Unsure.
* description of `Gong_12_None` (Primordial Symbols Law) and `Item_Gong12`
* technically all 3 description of Shendao laws, but it's understandable as is so not an issue
* description of `Item_BodyPractice_XianDaoJingHua`, `Item_BodyPractice_XianSui`, 
* Even 10,129's text
